#!/bin/bash

function invoke(){
	aws lambda invoke --function-name "$1"  "$2"
}

if test $# -ne 2
	then echo Usage: fun-name outputfile
	exit 1
fi

FUNC="$1"
FILE="$2"

for i in {1..300}
	do invoke "$FUNC" "$FILE" &
	sleep 3
done

jobs > lambdaJob$$.txt 
